# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19Boekak5q7bnHBIRQerwkbdi5XzWIkhh
"""

import streamlit as st
from transformers import BertTokenizer, TFBertForSequenceClassification
import numpy as np
import tensorflow as tf
import re

# Muat model dan tokenizer
tokenizer = BertTokenizer.from_pretrained('indobenchmark/indobert-base-p2')
model = TFBertForSequenceClassification.from_pretrained('indobenchmark/indobert-base-p2', num_labels=3)

# Fungsi untuk preprocessing dan prediksi
def predict_sentiment(text):
    max_len = 50
    # Preprocessing teks
    text = text.lower()
    text = re.sub(r'http\S+|www\S+|https\S+', '', text)
    text = re.sub(r'@\w+|#\w+', '', text)
    text = re.sub(r'[^\w\s]', '', text)
    text = text.strip()

    # Tokenisasi dan padding
    encoding = tokenizer.encode_plus(
        text,
        add_special_tokens=True,
        truncation=True,
        padding='max_length',
        max_length=max_len,
        return_tensors='tf'
    )

    # Prediksi
    prediction = model(encoding['input_ids'])[0]  # Ambil logits
    sentiment = np.argmax(prediction, axis=1)[0]

    if sentiment == 0:
        return "Negatif"
    elif sentiment == 1:
        return "Netral"
    else:
        return "Positif"

# Streamlit UI
st.title('Chatbot Analisis Sentimen')
user_input = st.text_input("Masukkan kalimat untuk analisis sentimen:")

if user_input:
    sentiment = predict_sentiment(user_input)
    st.write(f"Sentimen dari kalimat: {sentiment}")